- name: Installation et configuration de fail2ban
  become: true
  block:
    - name: Installer fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: true

    - name: Activer le service
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true

    - name: Copier la configuration fail2ban locale
      ansible.builtin.copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "0644"
      notify: Reload fail2ban
