all:
  hosts:
    dirqual1:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HOSTS').split(',')[0] }}"
    dirqual2:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HOSTS').split(',')[1] }}"
    dirqual3:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HOSTS').split(',')[2] }}"
    dirqual4:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HOSTS').split(',')[3] }}"
