- name: Mise à jour du système d'exploitation
  hosts: all
  serial: 1
  become: true
  roles:
    - os-upgrade
- name: Sécurisation
  hosts: all
  become: true
  roles:
    - env-vars
    - ssh
    - sshd
    - firewall
    - os
    - auditd
    - fail2ban
    - mail-root
