- name: Importer les variables d'environnement dans des variables Ansible
  tags:
    - import
  block:
    - name: "Affecter les variables d'environnement à des variables Ansible"
      ansible.builtin.set_fact:
        env_vars_mail_root_redirect: "{{ lookup('ansible.builtin.env', 'MAIL_ROOT_REDIRECT') }}"
        env_vars_host_user: "{{ lookup('ansible.builtin.env', 'HOST_USER') }}"
        env_vars_password_expiration: "{{ lookup('ansible.builtin.env', 'PASSWORD_EXPIRATION') }}"
        env_vars_ssh_key: "{{ lookup('ansible.builtin.env', 'PUBLIC_SSH_KEY') }}"

- name: Vérification de l’import des variables d’environnement
  tags:
    - checks
  block:
    - name: Vérifier que les variables sont définies et ont une chaîne de caractères non vide
      ansible.builtin.assert:
        that:
          - env_vars_mail_root_redirect is defined
          - env_vars_mail_root_redirect | length > 0
          - env_vars_host_user is defined
          - env_vars_host_user | length > 0
          - env_vars_password_expiration is defined
          - env_vars_password_expiration | length > 0
          - env_vars_ssh_key is defined
          - env_vars_ssh_key | length > 0
        fail_msg: "Les variables d'environnement ne sont pas définies ou sont vides."
  always:
    - name: Créer une variable ansible
      ansible.builtin.set_fact:
        env_vars_debug:
          env_vars_mail_root_redirect: "{{ env_vars_mail_root_redirect }}"
          env_vars_host_user: "{{ env_vars_host_user }}"
          env_vars_password_expiration: "{{ env_vars_password_expiration }}"
          env_vars_ssh_key: "{{ env_vars_ssh_key }}"

    - name: Afficher les variables importées
      ansible.builtin.debug:
        var: env_vars_debug
