- name: Configuration système (mise à jour et unattended-upgrades)
  become: true
  tags:
    - os
    - updates
  block:
    - name: Changer la durée de vie du mot de passe de l'utilisateur courant
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        password_expire_max: "{{ env_vars_password_expiration }}"

    - name: Mettre à jour le système
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Installer la mise à jour automatique
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Générer une minute aléatoire pour le reboot automatique
      ansible.builtin.set_fact:
        os_unattended_reboot_minute: "{{ 59 | random(seed=inventory_hostname) | int }}"

    - name: Déployer le fichier 20auto-upgrades avec minute aléatoire
      ansible.builtin.template:
        src: 20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: "0644"

    - name: Vérifier si un redémarrage est nécessaire
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: os_reboot_required

    - name: Redémarrer la machine si nécessaire
      ansible.builtin.reboot:
        msg: "Redémarrage automatique après mise à jour"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: os_reboot_required.stat.exists
  rescue:
    - name: Échec du bloc de configuration OS
      ansible.builtin.debug:
        var: ansible_failed_result
        msg: "Échec lors de l'application des tâches OS sur {{ inventory_hostname }}"
  always:
    - name: Rafraîchir le cache apt (assurance)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
