- name: Déploiement de la clé publique de l’utilisateur "{{ settings_host_user }}"
  become: true
  block:
    - name: Créer le dossier .ssh pour l’utilisateur "{{ settings_host_user }}"
      ansible.builtin.file:
        path: "/home/{{ settings_host_user }}/.ssh"
        state: directory
        owner: "{{ settings_host_user }}"
        group: "{{ settings_host_user }}"
        mode: "0700"

    - name: Copier la clé publique de l’utilisateur "{{ settings_host_user }}"
      ansible.builtin.copy:
        src: "{{ settings_ssh_key }}"
        dest: "/home/{{ settings_host_user }}/.ssh/authorized_keys"
        owner: "{{ settings_host_user }}"
        group: "{{ settings_host_user }}"
        mode: "0600"
