- name: Installation et activation du serveur SSH
  become: true
  block:
    - name: Installation du paquet OpenSSH
      ansible.builtin.apt:
        name: openssh-server
        state: present

    - name: Activation et démarrage du service SSH
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
