- name: Installation et configuration de Tailscale
  become: true
  tags:
    - tailscale
    - vpn
  block:
    - name: Ajouter la clé GPG de Tailscale
      ansible.builtin.apt_key:
        url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
        state: present

    - name: Ajouter le dépôt Tailscale
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
          https://pkgs.tailscale.com/stable/debian bookworm main"
        filename: tailscale
        state: present

    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: true

    - name: Installer tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present

    - name: Démarrer tailscale avec SSH activé
      ansible.builtin.command: tailscale up --ssh
      args:
        creates: /var/lib/tailscale/tailscaled.state
  rescue:
    - name: Échec de la configuration de Tailscale
      ansible.builtin.debug:
        msg: "Échec lors de la configuration de Tailscale sur {{ inventory_hostname }}"
  always:
    - name: Vérifier l'état du service tailscaled
      ansible.builtin.service_facts:
    - name: Afficher l'état du service tailscaled
      ansible.builtin.debug:
        var: ansible_facts.services['tailscaled.service']
