- name: Configuration du pare-feu UFW (Zero Trust simplifié)
  become: true
  tags:
    - firewall
    - ufw
  block:
    - name: Installer UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Définir la politique par défaut (incoming deny, outgoing allow)
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Définir la politique sortante par défaut (allow)
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Autoriser tout le trafic entrant depuis les autres serveurs du cluster
      community.general.ufw:
        direction: incoming
        rule: allow
        src: "{{ hostvars[item]['ansible_host'] | default(item) }}"
      loop: "{{ groups['all'] | difference([inventory_hostname]) }}"
      loop_control:
        label: "{{ hostvars[item]['ansible_host'] | default(item) }}"

    - name: Autoriser OpenSSH depuis Internet
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Activer le logging UFW
      community.general.ufw:
        logging: "on"

    - name: Activer et appliquer UFW
      community.general.ufw:
        state: enabled
        enabled: true
  rescue:
    - name: Échec de la configuration UFW
      ansible.builtin.debug:
        msg: "Échec lors de l'application des règles UFW sur {{ inventory_hostname }}"
  always:
    - name: Afficher l'état UFW après application
      ansible.builtin.command: ufw status verbose
      register: firewall_ufw_status
      changed_when: false
    - name: Afficher le résultat UFW
      ansible.builtin.debug:
        var: firewall_ufw_status.stdout
