- name: Configuration sécurisée du serveur SSH
  become: true
  tags:
    - ssh
    - sshd
  block:
    - name: Désactiver le login root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Restart SSH

    - name: Forcer l’authentification par clé
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart SSH

    - name: Désactiver ChallengeResponseAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?ChallengeResponseAuthentication"
        line: "ChallengeResponseAuthentication no"
        state: present
      notify: Restart SSH

    - name: Limiter le nombre de tentatives
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?MaxAuthTries"
        line: "MaxAuthTries 3"
        state: present
      notify: Restart SSH

    - name: Réduire le délai d’attente
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?LoginGraceTime"
        line: "LoginGraceTime 30s"
        state: present
      notify: Restart SSH

    - name: Activer le logging détaillé
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?LogLevel"
        line: "LogLevel VERBOSE"
        state: present
      notify: Restart SSH

    - name: Restreindre les utilisateurs autorisés
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?AllowUsers"
        line: "AllowUsers {{ env_vars_host_user }}"
        state: present
      notify: Restart SSH

    - name: Activer l’authentification par clé publique
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
        state: present
      notify: Restart SSH

    - name: Définir l'intervalle de vie client SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?ClientAliveInterval"
        line: "ClientAliveInterval 300"
        state: present
      notify: Restart SSH

    - name: Définir le nombre maximal de keepalive sans réponse
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?ClientAliveCountMax"
        line: "ClientAliveCountMax 3"
        state: present
      notify: Restart SSH
  rescue:
    - name: Échec de la configuration SSH
      ansible.builtin.debug:
        msg: "Échec lors de l'application de la configuration SSH sur {{ inventory_hostname }}"
  always:
    - name: Vérifier la configuration SSH effective
      # noqa 204
      ansible.builtin.command: grep -E '^(PermitRootLogin|PasswordAuthentication|ChallengeResponseAuthentication|MaxAuthTries|LoginGraceTime|LogLevel|AllowUsers|PubkeyAuthentication|ClientAliveInterval|ClientAliveCountMax)' /etc/ssh/sshd_config
      register: ssh_server_config_check
      changed_when: false
    - name: Afficher la configuration SSH effective
      ansible.builtin.debug:
        var: ssh_server_config_check.stdout_lines
