- name: Rediriger les mails root vers une adresse personnalisée
  become: true
  tags:
    - mail
    - root
  block:
    - name: Installer postfix (pour fournir /etc/aliases)
      ansible.builtin.apt:
        name: postfix
        state: present
    - name: Définir l'alias root dans /etc/aliases
      ansible.builtin.lineinfile:
        path: /etc/aliases
        regexp: "^root:"
        line: "root: {{ env_vars_mail_root_redirect }}"
        state: present
      notify: newaliases
  rescue:
    - name: Échec de la configuration de l'alias mail root
      ansible.builtin.debug:
        msg: "Échec lors de la configuration de l'alias mail root sur {{ inventory_hostname }}"
  always:
    - name: Appliquer la commande newaliases
      ansible.builtin.command: newaliases
      changed_when: false
